services:
  redroid5555:
    image: redroid/redroid:12.0.0-latest
    container_name: redroid5555
    privileged: true
    restart: unless-stopped
    volumes:
      - \${HOME}/data/redroid5555:/data
    ports:
      - "5559:5555"
    environment:
      - androidboot.redroid_width=1080
      - androidboot.redroid_height=2340
      - androidboot.redroid_dpi=434
      - androidboot.redroid_fps=60
      - androidboot.redroid_gpu_mode=guest
      - androidboot.selinux=permissive
    devices:
      - /dev/binder:/dev/binder
      - /dev/hwbinder:/dev/hwbinder
      - /dev/vndbinder:/dev/vndbinder
